---
title: "ANCOM"
author: "Judy-Malas"
date: "12/28/2021"
output: html_document
---

(Kaul et al., 2017)
https://www.frontiersin.org/articles/10.3389/fmicb.2017.02114/full

https://www.youtube.com/watch?v=A6o2nOnDsJU&t=1040s


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages, message=FALSE}
library(nlme)
library(tidyverse)
library(ggplot2)
library(compositions)
source("scripts/ancom_v2.1.R")
library(readr)
library(tidyverse)

```

#ANCOM


```{r load-phyloseq-objects}
ps_all <- readRDS("~/landfill-microcosms/data/live_samples_objects/ps_all.step2") 

```


```{r make-inputfiles-otu-tbl}

seqtab.ps_all <- ps_all@otu_table #extract the seq tab
metadata.ps_all <- ps_all@sam_data #extract the metadata table

otu_live <- as.data.frame(seqtab.ps_all)
otu_live.t <- t(otu_live) #this looks identical to otu_data from the example

write.csv(otu_live.t, "otu.live.t.csv")

otu_tble <- read.csv("otu.live.t.csv")

seqs <- otu_tble$X

rownames(otu_tble) = seqs

otu_tble <- otu_tble[,-1] #delete first column which is now unnesseary 
 

```

```{r metadata}

meta <- as.data.frame(metadata.ps_all)
write.csv(meta, "meta_live.csv")
meta_live <- read.csv("meta_live.csv")


meta_live <- meta_live %>% 
  dplyr::rename(Sample.ID = sample)

meta_live <- meta_live[, -1]

#add treatment variable
meta_live <- meta_live %>% 
  mutate(treatment =  #add a new column of data which specifies whether the samples have ACTUALLY been treated with a spike
           case_when(sample_time == "T1" ~ "None", 
                     sample_time == "T2" ~ "None", 
                    sample_time == "T3" ~ "None", 
                        sample_time == "T4" ~ "None", 
                        sample_time == "T5" ~ as.character(spike), 
                    sample_time == "T6" ~ as.character(spike))) 



```


## Step 1: Data preprocessing


```{r}

feature_table = otu_tble; sample_var = "Sample.ID"; group_var = NULL
out_cut = 0.05; zero_cut = 0.90; lib_cut = 1000; neg_lb = FALSE
prepro = feature_table_pre_process(feature_table, meta_live, sample_var, group_var, 
                                   out_cut, zero_cut, lib_cut, neg_lb)
feature_table = prepro$feature_table # Preprocessed feature table
meta_data = prepro$meta_data # Preprocessed metadata
struc_zero = prepro$structure_zeros # Structural zero info


```



## Step 2: ANCOM

```{r}

main_var = "treatment"; p_adj_method = "BH"; alpha = 0.05
adj_formula = NULL; rand_formula = NULL
t_start = Sys.time()

res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula)
t_end = Sys.time()
t_run = t_end - t_start # around 30s

write_csv(res$out, "res_full_time.csv")

```



## Step 3: Volcano Plot

```{r}

# Number of taxa except structural zeros
n_taxa = ifelse(is.null(struc_zero), nrow(feature_table), sum(apply(struc_zero, 1, sum) == 0))
# Cutoff values for declaring differentially abundant taxa
cut_off = c(0.9 * (n_taxa -1), 0.8 * (n_taxa -1), 0.7 * (n_taxa -1), 0.6 * (n_taxa -1))
names(cut_off) = c("detected_0.9", "detected_0.8", "detected_0.7", "detected_0.6")

# Annotation data
dat_ann = data.frame(x = min(res$fig$data$x), y = cut_off["detected_0.7"], label = "W[0.7]")

fig = res$fig +  
  geom_hline(yintercept = cut_off["detected_0.7"], linetype = "dashed") + 
  geom_text(data = dat_ann, aes(x = x, y = y, label = label), 
            size = 4, vjust = -0.5, hjust = 0, color = "orange", parse = TRUE)
fig  



```


How do we find out which features correspond to which taxa?
```{r}

taxatable <- ps_all@tax_table
taxatable <- as.data.frame(taxatable)

taxatable <- taxatable %>% 
  mutate(taxa_id = rownames(taxatable))

ancom_res_ps_all  <- full_join(ancom_res_ps_all, taxatable, by = "taxa_id")

```







